name: Temitope Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  localrunner-test:
    runs-on: [ self-hosted, local ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display runner info
        run: |
          echo "Running on $(hostname)"
          uname -a
